### PR TITLE
DS-125

### PR DESCRIPTION
**Pull request by FeLungs**
Fix https://github.com/yetanalytics/datasim/issues/77

### CODE REVIEW

**Review by milt — COMMENTED** [review]
These pass in cli and thanks for adding the tests. I'm curious, for the ones we originally authored, could we just replace the ones that don't pass? There might be some reason to keep the old ones around, hence the question.

**Comment by FeLungs** [comment]
I wasn't sure on that, I went with the `"fixed"` method because that was the pattern for the others and there was an existing invalid-profile test but I think you're right, its probably better to overwrite.

I'll make the change and push it up shortly

**Review by milt — APPROVED** [review]

**Comment by kelvinqian00** [comment]
Why not also overwrite the other two profiles you changed?

**Comment by FeLungs** [comment]
To distinguish between the profiles in the authored profiles repo and the versions here.

**Comment by kelvinqian00** [comment]
> To distinguish between the profiles in the authored profiles repo and the versions here.

Ah yes, since only TC3 was originally authored by us.

**Comment by FeLungs** [comment]
I authored the fixes based off the validation errors in the [issue](https://github.com/yetanalytics/datasim/issues/77). The TCCC issues here were identical to those in https://github.com/yetanalytics/project-pan/pull/41. 

I'm not aware of previously fixed versions of the profiles in `dev-resources/`

**Review by kelvinqian00 — APPROVED** [review]

**Pull request merged**
